# ========== Server ==========
server:
  port: 8080

# ========== MySQL ==========
spring:
  datasource:
    url: jdbc:mysql://localhost/writon-test?validationQuery="select 1"?serverTimezone=Asia/Seoul
    username: root
    password: Cn37rqww@@!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none # ddl ?? ?? none, update, validate, create, create-drop
    properties:
      format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
    generate-ddl: true
    show-sql: true # sql ??

# ========== JWT ==========
jwt:
  secret: ${JWT_SECRET_KEY}

# ========== AWS S3 ==========
cloud:
  aws:
    s3:
      bucket: hoon-test-bucket
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false